site_name: 基于主动学习的警告排序优化

nav:
  - 项目介绍: index.md
  - 配置指南:
    - "运行环境": config/运行环境.md
    - "配置文件": config/配置文件.md
    - "数据目录": config/数据目录.md
  - 运行指南:
    - "项目选择": run/项目选择.md
    - "项目下载与警告扫描": run/下载扫描.md
    - "特征提取": run/特征提取.md
    - "警告正误报标记": run/警告标记.md
    - "实验运行": run/实验运行.md
    - "项目运行": run/项目运行.md
  - "开发指南":
    - "通用部分": dev/通用部分.md
    - "实验部分": dev/实验部分.md
    - "系统部分": dev/系统部分.md

theme:
  name: "readthedocs"
  titles_only: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("python")
          selection:
            docstring_style: restructured-text
          rendering:
            show_source: false
            show_root_heading: true

extra_css: [ extra.css ]
